port: "8800"
db:
  username: "postgres"
  password: "VDKGJVsaKSClsHRCJMXKjlmbcQtuymDl"
  host: "monorail.proxy.rlwy.net"
  port: "19623"
  dbname: "railway"
  sslmode: "disabled"
  # username: "postgres"
  # password: "qwerty"
  # host: "localhost"
  # port: "5436"
  # dbname: "postgres"
  # sslmode: "disable"